spring:
  jackson:
    default-property-inclusion: non_null
  web:
    resources:
      #控制api文档访问, smart-doc生成的html静态api文档，生产服务器不需要暴露文档
      add-mappings: off
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
