spring:
  web:
    resources:
      #控制api文档访问, smart-doc生成的html静态api文档
      add-mappings: on
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#阿里云OSS参数
alibaba:
  cloud:
    access-key: LTAI4GFKKZSC4w9gCLfTcAZY
    secret-key: Vc8yXYHrVs9ioJ4AUNKFZZ4SykCTfA
    bucket-name: alphahub-test-bucket
    host-prefix: https://${alibaba.cloud.bucket-name}.${alibaba.cloud.oss.endpoint}
    oss:
      endpoint: oss-cn-shanghai.aliyuncs.com
