server:
  port: 30000
spring:
  application:
    name: lejing-third-party
  #运行环境: dev|test|prod
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#阿里云OSS参数
alibaba:
  cloud:
    access-key: LTAI4GFKKZSC4w9gCLfTcAZY
    secret-key: Vc8yXYHrVs9ioJ4AUNKFZZ4SykCTfA
    bucket-name: alphahub-test-bucket
    host-prefix: https://${alibaba.cloud.bucket-name}.${alibaba.cloud.oss.endpoint}
    oss:
      endpoint: oss-cn-shanghai.aliyuncs.com
